baseURL = 'https://raphapr.github.io'
languageCode = 'en-us'
title = 'raphapr'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[params]
  author = "raphapr | blog"
  description = "Here's a small corner of the internet where I share whatever strikes my fancy."
  menu_item_separator = " - "
  avatar = "avatar.jpg"
  favicon = "/favicon.ico"
  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/raphapr"
  [[params.social]]
    icon = "linkedin"
    name = "My LinkedIn"
    url = "https://www.linkedin.com/in/raphaelpr/"
